### ISSUE TITLE
Plan the Needs Assessment

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/higher-education-engagement#4]
# Context

* Start with GSF HE members and referrals from other volunteers
* Store everything within the GSF

# References

* https://docs.google.com/document/d/1SDdsB6NP8TN4NDDehQl5GpAjKh6rZVT7zJWhzcUy-kM/edit#heading=h.uh6yplca6wcb

# Actions

## Logistics

- [x] @russelltrow create GH issues for the each initial potential interviewee
  - [x] #7
  - [x] #8
  - [x] #9
  - [x] #10
  - [x] #11
  - [x] #12
  - [x] #13
- [x] Gather additional institutions from @aecurrie & @PindyBhullar
- [x] Create tracker for interviews
- [x] @tholewis write interview request email
- [x] @russelltrow finalise interview request email
- [x] Determine how to share potential interview slots with institutes 

## Interview Planning

- [x] #15

**Comment by tholewis** [comment]
_Here is the first draft of the invitation, feel free to amend as necessary! - Thomas_

**Subject: [Request] Green Software Foundation Discussion with Higher Education Institutions**

Thank you for reviewing this invitation to a conversation with you and the [Green Software Foundation](https://greensoftware.foundation/). 

We have put together a project to identify the needs of higher education institutions around Green Software and Sustainability. We know that there are a lot of things we could do, but we are embarking on a Needs Assessment activity so that we can take in your thoughts and needs that we may be able to address.

We would appreciate taking a brief moment of your time that works for you to discuss over a 30-minute video call questions similar to:

- What educational resources do you prefer? How do you prefer those resources to be delivered?
- How do you approach practical activities with students? Are they hands-on in labs? Are they open-source project contributions? Capstone projects?
- Would mentorship programs be of interest? What would they expect from such a program?
- Would you find value in a network with like-minded peers and professionals facilitated by the GSF?
- How is Sustainability being addressed at your institution?

Of course, it can be a free-form discussion as we would prefer to get insights from you how we can create an impactful Higher Education offering.

If you are interested in a discussion, we'd love to discuss this more with you! Let us know and we will try to find a time that works for you. Thanks in advance for your interest in being a part of this project.

Thank you again,
Green Software Foundation
